apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: brentwebapp
  
  ports:
    - name: http
      port: 80
      nodePort: 30080

  # Choose NodePort or ClusterIP
  type: NodePort